# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, dev, 3.x ]
  pull_request:
    branches: [ master, dev, 3.x ]

jobs:
  jdk8:
    runs-on: ubuntu-latest
    name: Java 8 job
    steps:
      - uses: actions/checkout@v2
      - name: Setup redis 1
        uses: getong/redis-action@v1
        with:
          redis version: '3.2.3'
          host port: 6380
          container port: 6380
          redis password: 'test'
      - name: Setup redis 2
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: false
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: false
      - name: Version
        run: java -version
      - name: Compile
        run: mvn clean package -P CI --batch-mode --quiet --global-toolchains ./toolchains.xml
      - name: Test
        run: mvn clean test jacoco:report coveralls:report --batch-mode --quiet --global-toolchains ./toolchains.xml
  jdk11:
    runs-on: ubuntu-latest
    name: Java 11 job
    steps:
      - uses: actions/checkout@v2
      - name: Setup redis 1
        uses: getong/redis-action@v1
        with:
          redis version: '3.2.3'
          host port: 6380
          container port: 6380
          redis password: 'test'
      - name: Setup redis 2
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: false
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: false
      - name: Version
        run: java -version
      - name: Compile
        run: mvn clean package -P CI --batch-mode --quiet --global-toolchains ./toolchains.xml
      - name: Test
        run: mvn clean test jacoco:report coveralls:report --batch-mode --quiet --global-toolchains ./toolchains.xml

